#!/bin/bash
# =============================================================================
#  install.sh — TeslaBMS-ESP32 standalone Venus OS driver installer
#
#  Tested on Venus OS v3.x (GX large / Cerbo GX / Raspberry Pi GX)
#
#  What this script does
#  ─────────────────────
#  1.  Verifies Venus OS ≥ v3.00 is installed.
#  2.  Copies dbus-teslabms.py to /data/etc/dbus-teslabms/
#  3.  Creates a daemontools-compatible service directory under
#      /service/dbus-teslabms/ so that runit (the Venus OS service manager)
#      starts the driver automatically on boot and restarts it on crash.
#  4.  Hooks enable.sh into /data/rc.local so the service survives a
#      Venus OS firmware update (the /data partition persists across updates).
#
#  Usage
#  ─────
#  1.  Place dbus-teslabms.py and this install.sh in the same directory.
#  2.  Run:   bash install.sh
#  3.  Check the log:  tail -f /var/log/dbus-teslabms/current
#
#  To uninstall:
#      bash /data/etc/dbus-teslabms/uninstall.sh
#
#  Directory layout after install
#  ──────────────────────────────
#  /data/etc/dbus-teslabms/
#      dbus-teslabms.py      ← the Python driver
#      install.sh            ← this file (kept for reference)
#      uninstall.sh          ← generated by install
#      enable.sh             ← (re-)creates the /service symlink on boot
#
#  /service/dbus-teslabms/   ← runit service directory
#      run                   ← executes the driver
#      log/run               ← executes the multilog logger
#
#  /var/log/dbus-teslabms/   ← rotating log (multilog)
# =============================================================================

set -euo pipefail

# ── Colour helpers ─────────────────────────────────────────────────────────
RED='\033[0;31m';  GREEN='\033[0;32m'
YELLOW='\033[1;33m'; NC='\033[0m'
info()    { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }

# ── Paths ──────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTALL_DIR="/data/etc/dbus-teslabms"
SERVICE_DIR="/service/dbus-teslabms"
LOG_DIR="/var/log/dbus-teslabms"
DRIVER_SRC="${SCRIPT_DIR}/dbus-teslabms.py"
RC_LOCAL="/data/rc.local"

# ── 1. Pre-flight checks ────────────────────────────────────────────────────
info "Checking environment …"

# Must run as root
[[ $EUID -eq 0 ]] || error "This script must be run as root (try: sudo bash install.sh)"

# dbus-teslabms.py must be present next to this script
[[ -f "$DRIVER_SRC" ]] || error "dbus-teslabms.py not found in ${SCRIPT_DIR}. Place both files in the same directory."

# Verify Venus OS version ≥ 3.00
VENUS_VERSION_FILE="/opt/victronenergy/version"
if [ -f "$VENUS_VERSION_FILE" ]; then
    VENUS_VER=$(cat "$VENUS_VERSION_FILE" | tr -d '\n\r')
    info "Detected Venus OS version: ${VENUS_VER}"

    # Extract major version number (e.g. "v3.71" → 3)
    MAJOR=$(echo "$VENUS_VER" | tr -d "v" | cut -d. -f1)

    if [ -z "$MAJOR" ] || [ "$MAJOR" -lt 3 ]; then
        error "Venus OS v3.00 or newer is required. Found: ${VENUS_VER}"
    fi
else
    warn "Cannot find ${VENUS_VERSION_FILE} — skipping version check."
fi

# Confirm that velib_python is present (needed at driver runtime)
VELIB="/opt/victronenergy/dbus-serialbattery/ext/velib_python"
if [[ ! -d "$VELIB" ]]; then
    warn "velib_python not found at ${VELIB}."
    warn "The driver may fail to start if dbus-serialbattery is not installed."
    warn "Install dbus-serialbattery (mr-manuel) first, or adjust VELIB_PATH in dbus-teslabms.py."
fi

# ── 2. Create installation directory ───────────────────────────────────────
info "Creating installation directory: ${INSTALL_DIR}"
mkdir -p "${INSTALL_DIR}"

# ── 3. Copy the driver ──────────────────────────────────────────────────────
info "Copying dbus-teslabms.py …"
cp -f "${DRIVER_SRC}" "${INSTALL_DIR}/dbus-teslabms.py"
chmod 755 "${INSTALL_DIR}/dbus-teslabms.py"

# Also copy this install script for reference
cp -f "${BASH_SOURCE[0]}" "${INSTALL_DIR}/install.sh" 2>/dev/null || true

# ── 4. Write enable.sh ──────────────────────────────────────────────────────
#  enable.sh is called by rc.local on every boot.  It (re-)creates the runit
#  service directory so the driver survives a Venus OS firmware update.
info "Writing enable.sh …"
cat > "${INSTALL_DIR}/enable.sh" << 'ENABLE_SH'
#!/bin/bash
# enable.sh — (re-)creates the runit service for dbus-teslabms
# Called by /data/rc.local on every boot.
set -euo pipefail

INSTALL_DIR="/data/etc/dbus-teslabms"
SERVICE_DIR="/service/dbus-teslabms"
LOG_DIR="/var/log/dbus-teslabms"

# Create log directory if missing
mkdir -p "${LOG_DIR}"

# Create runit service directory
mkdir -p "${SERVICE_DIR}/log"

# ── log/run: hand off stdout/stderr to multilog (rotating, 500 kB × 4 files)
cat > "${SERVICE_DIR}/log/run" << 'LOG_RUN'
#!/bin/sh
exec multilog t s500000 n4 /var/log/dbus-teslabms
LOG_RUN
chmod 755 "${SERVICE_DIR}/log/run"

# ── run: the actual service entry point
cat > "${SERVICE_DIR}/run" << 'SVC_RUN'
#!/bin/sh
# Forward SIGTERM to the Python process so it can clean up
trap 'kill -TERM $PID' TERM INT

exec 2>&1

# Python 3 on Venus OS v3.x lives at /usr/bin/python3
# The driver uses gi.repository.GLib (available in Venus OS v3.x)
python3 /data/etc/dbus-teslabms/dbus-teslabms.py &

PID=$!
wait $PID
EXIT_STATUS=$?
exit $EXIT_STATUS
SVC_RUN
chmod 755 "${SERVICE_DIR}/run"

echo "[enable.sh] Service directory (re-)created at ${SERVICE_DIR}"
ENABLE_SH
chmod 755 "${INSTALL_DIR}/enable.sh"

# ── 5. Write uninstall.sh ───────────────────────────────────────────────────
info "Writing uninstall.sh …"
cat > "${INSTALL_DIR}/uninstall.sh" << 'UNINSTALL_SH'
#!/bin/bash
# uninstall.sh — removes the TeslaBMS driver and service
set -euo pipefail

SERVICE_DIR="/service/dbus-teslabms"
INSTALL_DIR="/data/etc/dbus-teslabms"
RC_LOCAL="/data/rc.local"

echo "Stopping service …"
svc -d "${SERVICE_DIR}" 2>/dev/null || true
sleep 1

echo "Removing service directory …"
rm -rf "${SERVICE_DIR}"

echo "Killing any remaining driver processes …"
pkill -f "dbus-teslabms.py" 2>/dev/null || true

echo "Removing rc.local entry …"
sed -i '/dbus-teslabms/d' "${RC_LOCAL}" 2>/dev/null || true

echo "Removing installation directory …"
rm -rf "${INSTALL_DIR}"

echo "Uninstall complete."
UNINSTALL_SH
chmod 755 "${INSTALL_DIR}/uninstall.sh"

# ── 6. Run enable.sh to create the actual service directory ─────────────────
info "Running enable.sh to create runit service …"
bash "${INSTALL_DIR}/enable.sh"

# ── 7. Hook enable.sh into rc.local (survives firmware updates) ─────────────
info "Hooking enable.sh into ${RC_LOCAL} …"

# Create rc.local if it does not exist yet
if [[ ! -f "$RC_LOCAL" ]]; then
    echo "#!/bin/bash" > "$RC_LOCAL"
    chmod 755 "$RC_LOCAL"
fi

HOOK_LINE="bash /data/etc/dbus-teslabms/enable.sh >> /data/etc/dbus-teslabms/startup.log 2>&1"

# Add the line only once (grep -qxF checks for exact line match)
if grep -qxF "$HOOK_LINE" "$RC_LOCAL"; then
    info "rc.local hook already present — skipping."
else
    echo "$HOOK_LINE" >> "$RC_LOCAL"
    info "rc.local hook added."
fi

# ── 8. Start the service ─────────────────────────────────────────────────────
info "Starting dbus-teslabms service …"
# Give runit a moment to notice the new service directory
sleep 2
# svc -u sends SIGCONT to a down service, or starts it if not yet supervised
svc -u "${SERVICE_DIR}" 2>/dev/null || true

# ── 9. Done ─────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  TeslaBMS-ESP32 driver installed successfully!            ${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
echo ""
echo "  Service:      ${SERVICE_DIR}"
echo "  Log:          tail -f /var/log/dbus-teslabms/current"
echo "  Status:       svstat ${SERVICE_DIR}"
echo "  Stop:         svc -d ${SERVICE_DIR}"
echo "  Start:        svc -u ${SERVICE_DIR}"
echo "  Uninstall:    bash ${INSTALL_DIR}/uninstall.sh"
echo ""
echo "  D-Bus path:   com.victronenergy.battery.teslabms"
echo "  Inspect live: dbus-spy"
echo "    or:         dbus -y com.victronenergy.battery.teslabms / GetValue"
echo ""
echo "  Commands from any terminal:"
echo "    Shutdown:   dbus -y com.victronenergy.battery.teslabms /Control/Shutdown SetValue %1"
echo "    Startup:    dbus -y com.victronenergy.battery.teslabms /Control/Startup  SetValue %1"
echo ""